### ISSUE TITLE
Error message: "undefined is not a function".

### ISSUE THREAD

**Issue by samuele-artuso** [danielbrodin/atom-project-manager#186]
After upgrading to version 2.7.1 I get this error message when I start Atom: `undefined is not a function`.

I can reproduce the bug with any later version. I can't track it down though. My `projects.cson` file seems to be valid and all the paths listed in there do exist on my file system.

![error](https://cloud.githubusercontent.com/assets/3853889/12305384/706e6b7e-ba2c-11e5-9142-3be27ecf0812.png)

**Comment by danielbrodin** [comment]
This should be fixed. If it's not for you, you can try to restart atom, update atom, delete the `.atom/compile-cache` folder and it should fix it.

**Comment by samuele-artuso** [comment]
Still getting the same error.

**Comment by acorbi** [comment]
@samuele-artuso Im still having the issue as well. @danielbrodin Followed your instructions without success... any hints?

**Comment by danielbrodin** [comment]
If you open the console from view > developer > toggle developer tools and the console, do you get any errors there?

**Comment by samuele-artuso** [comment]
I checked out the console and there are no errors related to `project-manager`.

**Comment by samuele-artuso** [comment]
It seems to me that this change broke the package https://github.com/danielbrodin/atom-project-manager/commit/3c44f43c05b99dd50e4ad26f1b67ad182fe3d693#diff-be228df81b99a384aa50ad50bde7fca0

I tried to output `os.homedir` to the dev console and it outputted `undefined`. So I realized I was running an old version of Atom. Upgrade to latest version fixed the issue.

`os.homedir()` was added to Node only [recently](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-06-13-version-230-rvagg), so it won't work with old versions of Atom that come with node<2.3.0 bundled.

**Comment by danielbrodin** [comment]
Ah, great. Thanks for finding the issue @samuele-artuso

**Comment by acorbi** [comment]
updating to 1.4.0 worked for me as well. thanks @samuele-artuso @danielbrodin

**Comment by samuele-artuso** [comment]
[This line](https://github.com/danielbrodin/atom-project-manager/blob/master/package.json#L16) should be updated with the oldest version of Atom that comes with Node 2.3.0 bundled. I tried to find it out but didn't manage to.
